name: MacOS Release Build

on:
  schedule:
    # schedule build once per day
    - cron: "16 11 * * *"
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  TAG_NAME: "nightly"

jobs:
  build_macos:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        architecture: [x64] #Todo: Change to [x64, arm64] when github adds m1 builds later this year
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 1.59.0

    - name: Configure
      run: |
        cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DENABLE_TESTS=On -DCMAKE_PREFIX_PATH="/usr/local/opt/ffmpeg@4"

    - name: Build
      working-directory: build
      run: |
        make -j4

    - name: Tests
      working-directory: build
      run: |
        make UnitTest
        
    - name: Prepare artifact
      run: |
        mkdir dist
        cp -r build/src/Bin/OpenEnroth/OpenEnroth.app dist/
        cp -r resources/* dist/
        hdiutil create OpenEnroth.dmg -ov -volname "OpenEnroth" -fs HFS+ -srcfolder dist
        
    - name: Zip Folder For Release
      if: success() || failure()
      run: zip -r ./MacOS_${{ env.TAG_NAME }}_${{ matrix.configuration }}_${{ matrix.architecture }}.zip dist

    - name: Publish Release
      if: success() || failure()	
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        tag_name: ${{ env.TAG_NAME }}
        files: ${{ runner.os }}_${{ env.TAG_NAME }}_${{ matrix.configuration }}_${{ matrix.architecture }}.zip
        
