name: Style

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  check_style:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 1.59.0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglu1-mesa-dev zlib1g-dev
        sudo apt-get install -y libavformat-dev libavcodec-dev libswscale-dev
        sudo apt-get install -y libsdl2-dev

    - name: Configure
      run: |
        cmake -B build -DENABLE_TESTS=On

    - name: Check style
      working-directory: build
      run: |
        make check_style
